# Generated by Django 5.2.10 on 2026-01-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
