# Generated by Django 5.2.10 on 2026-01-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
